server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service

  data:
    mongodb:
    uri: mongodb://localhost:27017/catalog
    username: root
    password: root
    authentication-database: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


resilience4j:
  circuitbreaker:
     instances:
      movie-service:
       slidingWindowType: COUNT_BASED
       slidingWindowSize: 5
       failureRateThreshold: 50
       waitDurationInOpenState: 15000
       permittedNumberOfCallsInHalfOpenState: 3
       registerHealthIndicator: true
       allowHealthIndicatorToFail: false
       automaticTransitionFromOpenToHalfOpenEnabled: true
